apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
      - name: starbucks
        image: atanu03/starbucks:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
